### ISSUE TITLE
Deploy Script - Multiple Templates

### ISSUE THREAD

**Issue by RossMurr4y** [codeontap/gen3-azure#11]
EPIC codeontap/codeontap#40

```
As an infrastructure administrator I would like one single deployment 
script that trigger multiple azure ARM templates with their own parameter files.
```

In order to be able to deploy many different components with the one script, we require a way to be able to trigger all components from the same script, regardless of how many we have to run.

**Comment by RossMurr4y** [comment]
The default deployment script flow that comes from an exported template within Azure does the following:

1. Login to Az CLI
2.  Register with all providers specified
3. Create the new resource group if required.
4. deploy from template.json as per its resources/dependencies.

Step 4 does have some cursory checks included where it makes sure the template is valid syntax but it isn't terribly comprehensive. I also think Step 2 could be dynamic based on the resources in the template.json rather than have a hard-coded value for providers to register with.

I am going to try and impliment into this feature:
 - additional pre-implimentation checks via Test-AzResourceGroupDeployment cmdlet.
 - dynamic loading of the providers from the json template provided.

**Comment by roleyfoley** [comment]
components split out into individual components
