### ISSUE TITLE
Template management script

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#16]
Epic https://github.com/codeontap/codeontap/issues/41 

```
As a codeontap user I would like a codeontap script which deploys Azure Templates 
So that I can deploy azure rm templates using the same process as existing codeontap deployments 
```

Currently codeontap uses a bash scritpt based process to deploy templates generated by the codeontap template engine 
To deploy a generated template the manageStack.sh script is called ( https://github.com/codeontap/gen3/blob/master/aws/manageStack.sh) 

This script is responsible for a number of functions
- locating the template file to deploy based on the deployment unit provided 
- Creating/Updating/Deleting the deployment which is managed by this template 
- Recording the outputs provided by the template which will then be used by other components which are dependent on this deployment 

The current script only works when deploying to AWS using cloudformation, this ticket is to create an Azure ARM equivalent of this script based in bash and using a bash supported command line tool for Azure

**Comment by roleyfoley** [comment]
I think we can call this one closed with https://github.com/codeontap/gen3-azure/pull/19 
@RossMurr4y Do you agree?

**Comment by RossMurr4y** [comment]
@roleyfoley yep! Will make sure I add the "closes" to my future PR's.
