### ISSUE TITLE
Create Object Store Component

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#22]
EPIC https://github.com/codeontap/codeontap/issues/42

Following on from #21 rather than initially creating the baseline components we should try and deploy a standalone object store. 

It should be based on the existing [s3 component](https://github.com/codeontap/gen3/blob/master/providers/shared/components/s3/id.ftl) ( name will need to be changed on component ) and ideally use the same configuration options that are available already. 

The primary goal of this ticket is to test the theory of components being high level entities and their definition outlines a particular function you need in your solution and codeontap is responsible for turning them into real cloud provider resources

**Comment by RossMurr4y** [comment]
@roleyfoley is your intention here for gen3-azure to have a component named s3 initially and change it later, or should the component be generalised when addressing this ticket?

**Comment by roleyfoley** [comment]
Lets initially call it s3. I'd like to see how easily we can add a cross provider component in this ticket. Renaming the component type would require quite a few changes in the aws plugin 

I think the end component type would be objectstore. Storage would be too generic as it could cover block storage, file store or object storage

**Comment by RossMurr4y** [comment]
Completed in #42
