### ISSUE TITLE
New Component: Network

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#25]
The [network component]( https://github.com/codeontap/gen3/blob/2bc8a995feb9fc24edd49730ef5f6326def9195e/providers/shared/components/network/id.ftl) provides the base level private networking for a segment. Any resource which requires a private network should use the resources provided by this component. The network component does **not** provide access directly to other networks ( public gateways, nat gateways, vpn's etc) , this is handled by the gateway component. 

The network component provides
-  Virtual Network
    - An instance of a private network    
    - [AWS Resource]( https://aws.amazon.com/vpc/ ) 
- Subnets 
    - Which divide the network into logical sections based on components functionality, and region division ( availability zone) if required, or security requirements 
- Flow logging 
  - Provides metadata records on the network traffic flowing through the network 

The subnets used in the network component use the [Tier level configuration in the solution]( https://github.com/codeontap/gen3/blob/672be665f3a9af3f0f741091d442261bee4b07e1/providers/shared/masterData.ftl#L351 ) . Each tier which has been configured with components will have a subnet created for it in each availability zone ( for AWS this is required ). Subnets cannot be added outside of this process to ensure that components added to each tier always have a network to use 

The network component also has 2 subcomponents 

- RouteTable
   - A route table provides a list of gateways and conditions that can be used to forward traffic outside of the virtual network
   - Multiple route tables can be added to a network to allow different subnets/Tiers to use different routing rules 
   - A RouteTable is linked to subnets via the Tier configuration 

- Network ACL
  - Network ACL's provide high level network access control based on 4 tuple ( source port, source IP, destination port, destination IP ) rules
  - Network ACL's should not contain application specfic access controls and should instead focus on basic level controls such as no access from the internet or to blacklist known bad IP Addresses

**Comment by RossMurr4y** [comment]
@roleyfoley We have discussed having networkSecurityGroups in place of networkACL's for each subnet due to the way Azure handles this. Do you think it is also necessary/appropriate to have an NSG for the Vnet as well, or is that an unnecessary extra step given that all subnets will have their own?

**Comment by roleyfoley** [comment]
>Going over the route table configuration, i think my usage of them may differ slightly from the AWS implementation of them because of some of the things you get "out of the box" like the Gateways. Both Azure and AWS appear to have default route tables, but Azure also maintain them for you (unsure if AWS do this too). Do you think you could clarify in the ticket what the desired outcome is for each subnet? I can then pinch what I can from the AWS provider's state, and work with any advantages Azure might have at the same time.
>It's just not clear to me whether what's going on in the AWS provider is because you have to do it that way, or because its the desired component configuration.

@RossMurr4y AWS does have a default route table which they maintain, however you still need to attach the gateways to it and you can't put a nat gateway and IGW on the same route table since they both are usually used for the default route. 

So it is following the AWS requirements, but I would still think of this from a defence in depth approach. I.e. if we have said a subnet is not a public subnet and network interfaces in this subnet don't get public IP's they still shouldn't be part of a public network 

This also holds in Azure where you might want only certain subnets to use something like a VPN gateway to ensure only trusted hosts can get to your internal network .
