### ISSUE TITLE
New Component: Gateway

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#26]
Following on from #25  the [Gateway component](https://github.com/codeontap/gen3/blob/1b355071065b2f60deec83409ab92c2ddeb35217/providers/shared/components/gateway/id.ftl)  provides a link between the private network and other networks ( including the internet ) through the networks route table 

The Gateway component itself should look after provisioning the resources required to create the gateway. The Gateway Destination SubComponent links are then used to link a Gateway to a Network

Gateway Destinations should link to network Route Tables. This link should create a route table entry based on the destinations offered by the Gateway Destination, generally IP Address groups. 

In AWS we have the following engines for the gateway 
- [igw - Internet Gateway](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html) - Provides inbound and outbound internet access to resources hosted in the network  
- [nat - Network Address Translation](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html) - Provides outbound internet access to resources hosted in the network 
- [vpcendpoint](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-endpoints.html) - Provides outbound access to API endpoints offered by a cloud provider - This gateway allows for private only network resources to access cloud provider services without requiring full direct internet access

**Comment by RossMurr4y** [comment]
@roleyfoley - @ml019 and I have just had a good discussion on this component that I want to loop you in on.

Outbound traffic is handled quite differently  in Azure and a number of resources that you have to deploy in AWS are not necessary in Azure (if enabling outbound access is your sole purpose). I found [this article](https://lbadri.wordpress.com/2018/05/30/oubound-traffic-aws-vs-azure/) explains it really well. Essentially the major differences are though that:

- Azure by default will allow outbound access from within a virtualnetwork. A gateway resource is handled by Azure behind the scenes. 
- Similarly, network address translation is also handled by azure, including source network address translation where a public IP for an instance is not available.

We obviously do not want every virtual network and subnet to have outbound access - we want that to be determined by the tiers (that is my understanding anyway). So whilst we don't necessarily want to deploy any resources in place of the IGW or NAT, we need something to tell the vnet/subnet when its created if it should allow outbound access. Though we would have configuration for this in the solution, the Azure plugin would not contain components/services for the Gateway.

As for the vpc endpoint, Azure does have virtual network service endpoints and they are applied to a subnet. So here again we could use the solution configuration as a flag to tell the virtual network component upon its creation that there will be a subnet that has a service endpoint, and to create it.

What are your thoughts on this approach?

**Comment by roleyfoley** [comment]
Sounds good to me, the components are intended to show a functionality at a solution architecture view, how this function is implemented is really up to the component designer. If that just means the 'gateway' component has a security group allowing internet access where we have a default security group which blocks it the function has still be implemented. Also the less stuff we have to deploy the better :)

**Comment by ml019** [comment]
Less = More :-)

**Comment by RossMurr4y** [comment]
@roleyfoley @ml019 - Azure have released into preview their full-blown version of vpc endpoints, called Azure Private Link. I'll have to play around with it but despite being in preview I think it makes sense to spend the time now implementing this rather than coming back to do it later.

https://azure.microsoft.com/en-au/blog/announcing-azure-private-link/

**Comment by roleyfoley** [comment]
Yeah sounds good. We have this in the gateway for AWS at the moment as interface vpc endpoints so the component level config should be available
