### ISSUE TITLE
Provider Component Support: lb - application

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#28]
A [load balancer component](https://github.com/codeontap/gen3/blob/c9b447542bb1aecc13e84f5543091c12fadd79e2/providers/shared/components/lb/id.ftl) has two main purposes within a solution 
- Distributing client traffic between multiple instances of the same application 
- Providing a fixed endpoint to access the application 

On top of this for HTTPS based traffic it should also be able to provided HTTPS offload capabilities for backend applications. This allows for centralised certificate management and move the decryption processing requirements away from the application services to the load balancer.

The load balancer component itself provides the actual load balancer with the SubComponent PortMapping providing the rules to distribute traffic  to different applications. For HTTP(s) application this can include information from the HTTP protocol including host headers or request paths and queries. For non HTTP(s) applications this falls back to Destination Port based routing only. 

The load balancer does not control which applications consume a Port Mapping. Instead the application service links to a Load balancer port mapping and registers itself with the Portmapping. 

For AWS we have 3 engines available 
 - **application** which uses the [Application Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html) and can only be used for HTTP(s) traffic, but also provides a collection of extra services for managing client traffic 
 - **network** which use the [Network Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html), which can be use for any TCP or UDP based traffic but cannot use any information provided in the packet above layer3/4 of the OSI stack ( destination port only ) 
- **classic** which uses the [Classic Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/introduction.html), which can be used for both HTTP(s) and TCP/UDP traffic  but lacks some of the specific functionality and performance of the other two

**Comment by RossMurr4y** [comment]
@roleyfoley and I have had an offline discussion - adding the outcomes of it here for context.

The resources that will likely eventually make up the Load Balancer component of the Azure plugin are the Application Gateway and the "Load Balancer" resources. The Application Gateway would be the equivalent of AWS's Application Load Balancer and the Load Balancer would equate to the Network Load Balancer. However after reviewing the complexity of the Application Gateway component in Azure and confirming that a Django stack would use that over the "Load Balancer" resource within the component we both agreed that we will create the component using just the Application Gateway for the time being and add in the Load Balancer resource option at a later stage.
