### ISSUE TITLE
Provider Component Support: CDN

### ISSUE THREAD

**Issue by roleyfoley** [codeontap/gen3-azure#59]
The [CDN Component](https://github.com/codeontap/gen3/blob/39985ad9075e4e115b90afe825bf532b111681d9/providers/shared/components/cdn/id.ftl) provides Content delivery support for other HTTP based components, including load balancers, Single Page Applications and S3 Buckets 

Our CDN focuses on HTTP/s based application traffic and includes a route subcomponent which uses URL path based conditions to route traffic to different components. 

Most providers also support integration with web application firewall services which offer layer 7 level security rule detection of common attacks 

In AWS this is implemented with [CloudFront](https://aws.amazon.com/cloudfront/) as the primary service with firewall support provided through [WAF](https://aws.amazon.com/waf/)

For Azure the services would be 

- FrontDoor -  https://azure.microsoft.com/en-au/services/frontdoor/
- Web Application Firewall - https://docs.microsoft.com/en-us/azure/web-application-firewall/ 

Both services should be deployed as part of the same component 
Rules for the WAF should be sourced from our existing WAF support 

- WAF Rules - https://github.com/codeontap/gen3/blob/e4f1368ad87eb173205d9a809fe8df04e09937c8/providers/shared/references/WAFRule/id.ftl 
- WAF Rule Groups - https://github.com/codeontap/gen3/blob/e4f1368ad87eb173205d9a809fe8df04e09937c8/providers/shared/references/WAFRuleGroup/id.ftl
- WAF Conditions - https://github.com/codeontap/gen3/blob/e4f1368ad87eb173205d9a809fe8df04e09937c8/providers/shared/references/WAFCondition/id.ftl

The CDN Component is deployed as a standalone component however without content to distribute it won't actually work. Since the different content sources are so varied this is intentional

**Comment by RossMurr4y** [comment]
I have reviewed these requirements and I propose the following MVP to get up and running fast, with the intention of revisiting the setup logic of the component as necessary.

Services & Resources: 
> microsoft.network/frontDoors 
- [ ] all attributes / settings.
> microsoft.network/FrontDoorWebApplicationFirewallPolicies
- [ ] all attributes / settings.

Component: azure / cdn
- [ ] component state file where suboccurrences are processed first, creating routing rule objects per subcomponent. Then the occurrence is processed, creating FrontDoor (consuming the rules) + WAFPolicies
- [ ] skeleton component setup, with minimal logic and essentially just implementing the state.

I will revisit this list as pieces are contributed.

**Comment by roleyfoley** [comment]
Sounds great, one of these please
